In [ ]:
import pandas as pd

df = pd.DataFrame({
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
})

df

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [ ]:
display(df.head(1))

  name  score gender
0  Tom     85      男

In [ ]:
import pandas as pd

data = [[1, "A"], [2, "B"], [3, "C"]]
df2 = pd.DataFrame(data, columns=['id', 'tag'])

df2  # 直接显示表格

   id tag
0   1   A
1   2   B
2   3   C

In [ ]:
df[['score', 'gender']]

   score gender
0     85      男
1     92      女
2     78      男

In [ ]:
df.loc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [ ]:
df[df['score'] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [ ]:
# 创建 DataFrame
data = {"x": [1, None, 3], "y": [None, 5, 6]}
df2 = pd.DataFrame(data)


display(df2)

# 检测缺失值（布尔矩阵）

display(df2.isna())

# 统计每列缺失值数量

display(df2.isna().sum())

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

       x      y
0  False   True
1   True  False
2  False  False

x    1
y    1
dtype: int64

In [ ]:

df_fill0 = df.fillna(0)

display(df_fill0)


df_dropna = df.dropna()

display(df_dropna)
display(df_dropna)

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
})

print("=== 1. 按 gender 分组，score 的均值和最大值 ===")
display(df.groupby('gender')['score'].agg(['mean', 'max']))

print("\n=== 2. 按 gender 分组，统计每组人数 ===")
display(df.groupby('gender').size())

=== 1. 按 gender 分组，score 的均值和最大值 ===

        mean  max
gender
女       92.0   92
男       81.5   85

=== 2. 按 gender 分组，统计每组人数 ===

gender
女    1
男    2
dtype: int64

In [ ]:
# 升序排序（默认 ascending=True，可以省略）
df_sorted = df.sort_values(by='score', ascending=True)
df_sorted

    name  score gender
2   Mike     78      男
0    Tom     85      男
1  Jerry     92      女

In [ ]:
# 添加一行重复数据（Tom, 85, 男）
new_row = pd.DataFrame([{'name': 'Tom', 'score': 85, 'gender': '男'}])
df_with_dup = pd.concat([df, new_row], ignore_index=True)

print("添加重复行后：")
display(df_with_dup)

# 去重（默认保留第一次出现的行）
df_deduped = df_with_dup.drop_duplicates()

print("\n去重后：")
display(df_deduped)

添加重复行后：

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男
3    Tom     85      男

去重后：

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [ ]:
import pandas as pd

# ========== 1. 横向合并 ==========
df1 = pd.DataFrame({"id": [1, 2], "name": ["X", "Y"]})
df2 = pd.DataFrame({"id": [1, 2], "age": [20, 30]})
print("=== 横向合并 ===")
print("df1：")
display(df1)
print("df2：")
display(df2)
df_merged = pd.merge(df1, df2, on="id")
print("合并后：")
display(df_merged)

# ========== 2. 纵向拼接 ==========
df_a = pd.DataFrame({"val": [1, 2]})
df_b = pd.DataFrame({"val": [3, 4]})
print("\n=== 纵向拼接 ===")
print("df_a：")
display(df_a)
print("df_b：")
display(df_b)
df_concat = pd.concat([df_a, df_b], axis=0, ignore_index=True)
print("拼接后：")
display(df_concat)

=== 横向合并 ===
df1：

   id name
0   1    X
1   2    Y

df2：

   id  age
0   1   20
1   2   30

合并后：

   id name  age
0   1    X   20
1   2    Y   30

=== 纵向拼接 ===
df_a：

   val
0    1
1    2

df_b：

   val
0    3
1    4

拼接后：

   val
0    1
1    2
2    3
3    4

In [ ]:
import pandas as pd

# 1. 创建并转换时间列
dates_str = ["2025-01-01", "2025-01-02", "2025-01-03"]
df = pd.DataFrame({"date": dates_str})
df["date"] = pd.to_datetime(df["date"])

print("=== 转换后数据 ===")
display(df)
print("date 列数据类型：", df["date"].dtype)

# 2. 提取月份、星期
df["month"] = df["date"].dt.month
df["weekday_num"] = df["date"].dt.weekday
df["weekday_name"] = df["date"].dt.day_name()

print("\n=== 提取月份和星期后 ===")
display(df)

=== 转换后数据 ===

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03

date 列数据类型： datetime64[us]

=== 提取月份和星期后 ===

        date  month  weekday_num weekday_name
0 2025-01-01      1            2    Wednesday
1 2025-01-02      1            3     Thursday
2 2025-01-03      1            4       Friday

In [ ]:
import pandas as pd
import numpy as np

# 1. 原始数据
df = pd.DataFrame({
    'name': ['Tom', 'Jerry', 'Mike'],
    'score': [85, 92, 78],
    'gender': ['男', '女', '男']
})
print("=== 原始数据 ===")
display(df)

# 2. 标准化 score
mean_score = df['score'].mean()
std_score = df['score'].std()
df['score_std'] = (df['score'] - mean_score) / std_score
print("\n=== 标准化后数据 ===")
display(df)

# 3. 透视表（按 gender 求 score 中位数）
pivot = df.pivot_table(index='gender', values='score', aggfunc='median')
print("\n=== 透视表（gender × score 中位数） ===")
display(pivot)

=== 原始数据 ===

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

=== 标准化后数据 ===

    name  score gender  score_std
0    Tom     85      男        0.0
1  Jerry     92      女        1.0
2   Mike     78      男       -1.0

=== 透视表（gender × score 中位数） ===

        score
gender
女        92.0
男        81.5